sparta-final/final-project

public/js/admin.js
public/js/userList.js
src/app.module.ts

PR: Fix/adminpage

---

public/js/useHistory.js
src/app.controller.ts
src/domain/qrcode/qrcode.controller.ts
src/domain/qrcode/qrcode.decorators.ts
src/domain/qrcode/qrcode.service.ts
views/index.ejs
views/test.ejs

PR: Feature/membership

---

public/js/admin.js
public/js/adminApprove.js
public/js/adminApproveDetail.js
public/js/businessMyInfo.js
public/js/comment.js
public/js/components.js
public/js/enrollFeed.js
public/js/enrollGym.js
public/js/feedUpdate.js
public/js/myInfo.js
public/js/myInfoBusiness.js
public/js/mypage.js
public/js/postReview.js
public/js/review.js
public/js/user-gym-history.js
public/js/userList.js
src/app.controller.ts

- 접근 권한 [FE] 처리
1. admin 페이지 경우 type=admin 아니면 '/' 이동 '접근 권한이 필요합니다.' admin 페이지
2. user 페이지 경우 type=user 아니면 user '/user/login' 이동 '일반 로그인이 필요한 서비스입니다.'
3. business 페이지 경우 type=business 아니면 '/business/login' 이동 '사업자 로그인이 필요한 서비스입니다.'
- 비로그인시 피드 댓글 조회 실패 문제 해결

PR : Feature/access control

---

public/css/adminApproveDetail.css
public/js/adminApprove.js
public/js/adminApproveDetail.js
public/js/gym.js
src/app.controller.ts
src/domain/admin/admin.service.ts
src/domain/gym/gym.controller.ts
src/domain/gym/gym.decorators.ts
src/domain/gym/gym.service.ts
views/admin/adminApproveDetail.ejs
views/components/head.ejs
views/gym/postGym.ejs

PR: Feature/fe.adminapprove

---

public/js/enrollGym.js
public/js/feed.js
public/js/gymDetail.js
public/js/mypage.js
src/domain/gym/gym.service.ts

PR : Fix : 가맹점 이름 등록 중복 가능하게 수정 #90

---

public/js/gym.js
public/js/map.js
views/components/head.ejs

PR: Feature/mapfix

---

public/js/gym.js
public/js/mypage.js
src/domain/payment/payment.controller.ts
src/domain/payment/payment.module.ts
src/domain/payment/payment.service.ts

Feat : 결제, 구독 취소 후 유저 멤버쉽 변경 로직 #86

---

public/js/gymUpdate.js
public/js/userList.js
src/domain/admin/admin.controller.ts
src/domain/gym/gym.service.ts

업체등록 멀티이미지 수정관련 코드 완성. 프론트 수정까지 완성

PR: Fix/gym update

---

public/css/admin.css
public/css/gymDetail.css
public/css/header.css
public/css/mypage.css
public/css/postReview.css
public/js/admin.js
public/js/adminApproveDetail.js
public/js/gymDetail.js
public/js/myInfo.js
public/js/mypage.js
public/js/postReview.js
public/js/review.js
public/js/reviewDetail.js
public/js/searchGym.js
public/js/useHistory.js
src/domain/review/review.service.ts
src/domain/user/user.service.ts
views/admin/admin.ejs
views/components/header.ejs
views/main/main.ejs
views/mypage/myinfo.ejs
views/mypage/usegym-history.ejs
views/review/postReview.ejs
views/review/reviewDetail.ejs

- 검색 디자인 작업
- 리뷰 관련 페이지 디자인 정리

PR : Design/total page

---

src/domain/gym/gym.service.ts

PR: Feat/anything

---

public/js/gym.js
views/gym/gymList.ejs

PR: Feat/gym scroll

---

public/js/feed.js
src/domain/user/user.controller.ts
src/domain/user/user.service.ts

작성자가 아닐 시 알럿 뜨면서 수정불가능. 삭제 오류시 알럿창 생성. 비

PR: Fix/feed update

---

public/js/admin.js
src/domain/admin/admin.service.ts

PR: Fix/get rank

---

public/js/comment.js
public/js/myInfo.js
public/js/myInfoBusiness.js
public/js/mypage.js
public/js/mypageBusiness.js
src/domain/business-user/business-user.service.ts
src/domain/user/user.service.ts
views/mypage/myinfoBusiness.ejs

Refactor : 개인, 사업자 회원 탈퇴 service 코드에서 .save => softDelete 로 변경, 일단 회원 탈퇴 기능은 보류해서 js 에도 일단 주석처리해 뒀습니다.
사업자 회원, 프로필 사진 제외 다른 정보 수정시 프로필 이미지가 디폴트 이미지로 변경되는 점 수정
Design : 사업자 회원정보 수정 페이지 수정

PR : Feature/delete business front

---

public/js/comment.js
public/js/enrollFeed.js
src/domain/auth/auth.service.ts
src/domain/auth/guard/jwt-access.guard.ts

Refatcor : auth 리팩토링 

---

public/css/main.css
public/js/gym.js
public/js/review.js
public/js/user-gym-history.js
src/domain/admin/admin.service.ts
src/domain/gym/gym.service.ts
src/domain/payment/payment.service.ts
src/domain/review/review.service.ts
src/domain/user/user.service.ts

RawQuery 와 데이터를 가져오는 방법이 다른 ORM 특성떄문에 삭제된 데이터를 전부 Null로 가져오는 이슈가 생겼는데
queryBuilder에 .where('### IS NOT NULL') 코드 작성하여 해결함

PR : FIx : 삭제된 데이터 떄문에 생기는 에러 해결

---

README.md
public/js/feed.js

Fix : peed 페이지에서 작성한 글 만 수정,삭제 버튼 버튼 나오게 수정
Docs : README.md 수정, 역할 분담 추가 필요, 최정 구현 범위는 모르겠음

PR : peed.js, README.md 수정

---

public/js/gym.js

PR: Feat/mylocation gym2

---

public/css/feed.css
public/css/postReview.css
public/js/feed.js

Fix : 피드 삭제, 수정 버튼 나오게하는 버튼, 작성자와 로그인 id 같으면 생성
Design : 피드 수정 페이지, 리뷰 쓰기 페이지 color 변경

PR : 피드 버튼 수정, 피드 수정, 리뷰 수정 CSS 수정

---

public/js/gym.js

PR: Fix/gymfix

---

public/js/feed.js
public/js/gym.js
public/js/searchGym.js
src/domain/feed/dto/infinity.dto.ts
src/domain/feed/feed.controller.ts
src/domain/feed/feed.service.ts
src/domain/gym/gym.controller.ts
src/domain/gym/gym.service.ts
views/gym/searchGym.ejs

PR: Feat/infinityscroll

---

public/css/gym.css
public/css/header.css
public/css/mypage.css
public/js/mypage.js
public/js/review.js
public/js/searchGym.js
public/js/user-gym-history.js
src/domain/payment/payment.service.ts
views/gym/searchGym.ejs
views/mypage/paymentDetails.ejs
views/review/reviewList.ejs

PR : Feature/memberout

---

public/css/gym.css
public/css/qrcode.css
public/css/user-login.css
public/js/gym.js
public/js/myInfo.js
public/js/searchGym.js
views/auth/admin-login.ejs
views/auth/business-login.ejs
views/auth/user-login.ejs
views/gym/gymList.ejs
views/main/main.ejs

카카오 로그인 시 비밀번호 수정 플레이스 홀더에 기본비밀번호 안내 적용

PR : Design : 각 기능별 설명 추가
